SmartDelivery/Controllers/NormalCustomerController.cs
using SmartDelivery.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SmartDelivery.Controllers
{
    public class NormalCustomerController : Controller
    {
        SmartDeliveryEntities db = new SmartDeliveryEntities();

        // GET: NormalCustomer
        public ActionResult Index(int? id, int? usertype)
        {
            if (!HomeController.Authenticated && usertype != 4)
            {
                return RedirectToAction("Index", "home");
            }

            if (id != null)
            {
                Customer customer = db.Customers.Find(id);
                Session["userName"] = customer.UserName;
                Session["userType"] = customer.UserType.ToString();
                Session["id"] = id;
                //set cookie to can access from hubs
                Business.SetCookie(id.ToString(), customer.CustomerType.ToString());
                return RedirectToAction("ViewHome");
            }
            else if (Session["id"] != null)
            {
                int ID = Convert.ToInt32(Session["id"]);
                Customer customer = db.Customers.Find(id);
                return RedirectToAction("ViewHome");
            }


            return RedirectToAction("Index", "home");
        }

        /// <summary>
        /// Profile Managament //////////////////////////////////////////////////////////////////////
        /// </summary>
        /// 

        [HttpGet]
        public ActionResult ViewProfile()
        {
            if(Session["id"] != null) { 
            int normalCustomerID = int.Parse(Session["id"].ToString());

            var normalCustomer = db.Customers.FirstOrDefault(n => n.ID == normalCustomerID);

            if (normalCustomer != null)
            {
                return View(normalCustomer);
            }
            else
            {
                return HttpNotFound();
            }
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult UpdateProfile(int? id)
        {
            if (Session["id"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Customer normalCustomer = db.Customers.FirstOrDefault(n => n.ID == id);
                if (normalCustomer == null)
                {
                    return HttpNotFound();
                }
                Session["photo"] = normalCustomer.Photo;
                Session["userName"] = normalCustomer.UserName;
                Session["oldPass"] = normalCustomer.PassWord;

                return View(normalCustomer);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult UpdateProfile(Customer customer , HttpPostedFileBase image)
        {
            if (image != null)
            {
                customer.Photo = new byte[image.ContentLength];
                image.InputStream.Read(customer.Photo, 0, image.ContentLength);
            }
            else
            {
                customer.Photo = (byte[])Session["photo"];
            }

            try
            {

                string oldUserName = Session["userName"].ToString();

                //Check if old username equal to the new or not
                if (customer.UserName != oldUserName)
                {
                    //check the username of the employee if exits or not 
                    Customer checkEmployeeExistInCustomers = new Customer();
                    checkEmployeeExistInCustomers = db.Customers.FirstOrDefault(emp => emp.UserName == customer.UserName);

                    Employee checkEmployeeExistInEmployees = new Employee();
                    checkEmployeeExistInEmployees = db.Employees.FirstOrDefault(emp => emp.UserName == customer.UserName);

                    if (checkEmployeeExistInCustomers != null || checkEmployeeExistInEmployees != null)
                    {
                        Response.Write("<script>alert('This UserName Is Not Available Type Another One !.');</script>");
                        return View(customer);
                    }
                }

                if(customer.PassWord != Session["oldPass"].ToString())
                {
                    customer.PassWord = Encryption.Encrypt(customer.PassWord);
                }
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                Response.Write("<script>alert('Customer Updated Successfully .');</script>");

                return RedirectToAction("ViewProfile");
            }
            catch
            {
                return View(customer);
            }
        }

        [HttpGet]
        public ActionResult DeleteAccount(int? id)
        {
            if (Session["id"] != null)
            {
                var customer = db.Customers.Find(id);
                if (customer == null)
                {
                    return HttpNotFound();
                }
                return View(customer);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult DeleteAccount(Customer _customer)
        {
            try
            {
                var customer = db.Customers.Find(_customer.ID);

                if (customer == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    // "0" Means that the customer deleted !
                    customer.Authorized = 0;
                    db.SaveChanges();
                    return RedirectToAction("LogOut", "Home");
                }
                
            }
            catch
            {
                return View(_customer);
            }
        }


        /////////////////////////////////////////////////////////////////////////////////////




        /// <summary>
        /// Request Managament //////////////////////////////////////////////////////////////////////
        /// </summary>
        /// list

        [HttpGet]
        public ActionResult ListDeliveryRequests()
        {
            if (Session["id"] != null)
            {
                Debug.WriteLine("----------------- " + HomeController.Authenticated);
                int customerId = int.Parse(Session["id"].ToString());

                var requests = db.DeliveryRequests.Where(request => request.CustomerID == customerId && request.StatusID != 4 && request.StatusID != 5).OrderByDescending(r => r.ID).ToList();

                return View(requests);
               
            }
            else {

                return RedirectToAction("Index", "home");
            }
                

        }

        [HttpGet]
        public ActionResult RequestDelivery()
        {
            if (Session["id"] != null)
            {
                //List of Shipment Types
                ViewBag.ShipmentTypeID = new SelectList(db.ShipmentTypes.ToList(), "ID", "Type");
                ViewBag.CostperKM = new SelectList(db.ShipmentTypes.ToList(), "ID", "PricePerKilo");
                return View();
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult RequestDelivery(DeliveryRequest deliveryRequest)
        {
            try
            {

                //List of Shipment Types
                
                //Debug.WriteLine("TOTAL COST : " + deliveryRequest.Cost);
                //Debug.WriteLine(" PAID : " + deliveryRequest.Paid);
                //Debug.WriteLine(" type : "+deliveryRequest.ShipmentTypeID);


                int customerID = int.Parse(Session["id"].ToString());

                deliveryRequest.CustomerID = customerID;
                deliveryRequest.StatusID = 1;  // "pending"
                

                if (Session["PaymentFlag"] != null)
                {
                    Debug.WriteLine(bool.Parse(Session["PaymentFlag"].ToString()) + " => PAID");
                    deliveryRequest.Paid = 2;
                    deliveryRequest.CurrentLocation = deliveryRequest.Source;
                    Session["PaymentFlag"] = null;
                }else { deliveryRequest.Paid = 1; }


                db.DeliveryRequests.Add(deliveryRequest);
                db.SaveChanges();
                return RedirectToAction("ListDeliveryRequests");

            }
            catch (Exception ex)
            {
                if(Session["PaymentFlag"] != null)
                Session["PaymentFlag"] = true;

                Debug.WriteLine("ERROR ! : " + ex.Message);
                ViewBag.ShipmentTypeID = new SelectList(db.ShipmentTypes.ToList(), "ID", "Type");
                ViewBag.CostperKM = new SelectList(db.ShipmentTypes.ToList(), "ID", "PricePerKilo");
                return View(deliveryRequest);
            }
        }


        [HttpGet]
        public ActionResult UpdateRequest(int? id)
        {
            if (Session["id"] != null)
            {
                //List of Shipment Types
                ViewBag.ShipmentType = new SelectList(db.ShipmentTypes.ToList(), "ID", "Type");
                ViewBag.CostperKM = new SelectList(db.ShipmentTypes.ToList(), "ID", "PricePerKilo");

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                DeliveryRequest deliveryRequest = db.DeliveryRequests.FirstOrDefault(d => d.ID == id);
                if (deliveryRequest == null)
                {
                    return HttpNotFound();
                }

                return View(deliveryRequest);
            }

SmartDelivery/Views/NormalCustomer/CancelOrder.cshtml
@model SmartDelivery.Models.Order

@{
    ViewBag.Title = "CancelOrder";
    Layout = "~/Views/Shared/_normalcustomerLayout.cshtml";
}

<h2 class="text-center">Cancel Order</h2>
<h3 class="text-center">Are you sure you want to Cancel this Order?</h3>

<div class="center-the-content">
    <hr />
    <dl class="dl-horizontal">
        <dd>
            @foreach (var image in Model.Offer.OfferImages)
            {
                var i = 0;
                var base64 = Convert.ToBase64String(image.Image);
                var imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                <img src='@imgsrc' style="max-width:100px;max-height:100px" class="img-thumbnail" />
                i++;
                if (i == 1)
                {
                    break;
                }
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Offer.OfferDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offer.OfferDescription)
        </dd>
        

        <dt>
            @Html.DisplayNameFor(model => model.OrderStatu.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderStatu.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancel Order" class="btn" />
        </div>
    }
</div>
<a href="@Url.Action("ListAllPurchases")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/NormalCustomer/CancelRequest.cshtml
@model SmartDelivery.Models.DeliveryRequest

@{
    ViewBag.Title = "CancelRequest";
    Layout = "~/Views/Shared/_normalcustomerLayout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script type="text/javascript">

    function initAutocomplete() {

        var geocoder = new google.maps.Geocoder;


        var service = new google.maps.DistanceMatrixService();
        var sourceName = '@Model.Source';
        var destinationName = '@Model.Destination';
        var latlngStr1 = sourceName.split(',');
        var latlngStr2 = destinationName.split(',');
        var latlng1 = { lat: parseFloat(latlngStr1[0]), lng: parseFloat(latlngStr1[1]) };
        var latlng2 = { lat: parseFloat(latlngStr2[0]), lng: parseFloat(latlngStr2[1]) };
    
        geocoder.geocode({ 'location': latlng1 }, function (results, status) {
            if (status === 'OK') {
                if (results[0]) {

                    document.getElementById("_from").innerHTML = results[0].formatted_address;

                } else {
                    window.alert('No results found');
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });
        geocoder.geocode({ 'location': latlng2 }, function (results, status) {
            if (status === 'OK') {
                if (results[0]) {

                    document.getElementById("_to").innerHTML = results[0].formatted_address;

                } else {
                    window.alert('No results found');
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });


        service.getDistanceMatrix({
            origins: [latlng1],
            destinations: [latlng2],
            travelMode: google.maps.TravelMode.DRIVING,
            unitSystem: google.maps.UnitSystem.METRIC,
            avoidHighways: false,
            avoidTolls: false
        }, function (response, status) {
            if (status == google.maps.DistanceMatrixStatus.OK &&
                            response.rows[0].elements[0].status != "ZERO_RESULTS") {
                var distance = response.rows[0].elements[0].distance.value;
                distance = distance / 1000;

                var duration = response.rows[0].elements[0].duration.value;

                duration = parseFloat(duration / 60).toFixed(2);
                document.getElementById("_calculatedDistance").innerHTML = distance + " km";
                document.getElementById("__deliveryTime").innerHTML = duration + " minutes";



            }
        });





    }//end initAuto


</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARZj829jcIqy8ik7UKOwIT_CynjqIe4e0&libraries=places&callback=initAutocomplete"></script>
<h2 class="text-center">CancelRequest</h2>
<h3 class="text-center">Are you sure you want to Cancel this?</h3>
<div class="center-the-content">
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerID)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.ShipmentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipmentDescription)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ShipmentWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipmentWeight)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Source)
        </dt>

        <dd>
            <label id="_from"></label>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            <label id="_to"></label>
        </dd>
        <dt>
            Distance
        </dt>

        <dd>
            <label id="_calculatedDistance"></label>
        </dd>

        <dt>
          Expected Delivery Time
        </dt>

        <dd>
            <label id="__deliveryTime"></label>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancel" class="btn" /> 
        </div>
    }
</div>
@*<a href="@Url.Action("ListDeliveryRequests")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>*@
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/NormalCustomer/Chat.cshtml
@model IEnumerable<SmartDelivery.Models.Message>

@{
    ViewBag.Title = "Chat";
    Layout = "~/Views/Shared/_normalcustomerLayout.cshtml";
}
@*<h2>NormalCustomerChattingBox</h2>*@
<html>
<head>
    <link rel="stylesheet" href="~/Content/ChatStyle29_5.css" />
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="chat-header col-md-12 text-center">@ViewBag.DeliveryMan_FullNAme</div>

            <div class="chat-box col-md-12" id="msgss">
                <div class="col-md-12 messeges" id="chat-box-content">
                    <ul id="ulmessages">
                        @foreach (var item in Model)
                        {
                            int MyID = int.Parse(Session["id"].ToString());
                            if (item.SenderID == MyID)
                            {
                                <li class="bg-primary send-msg" id="sent_message"
                                   @{  string Time = item.Sent_DateTime.ToString("h:mmtt");}
                                 title=@Html.DisplayFor(modelItem => Time)>
                                    @Html.DisplayFor(modelItem => item.MessageContent)
                                </li>
                            }
                            else
                            {
                                <li>
                                    <div class="receive-msg" data-toggle="tooltip" data-placement="top" title=@Html.DisplayFor(modelItem => item.Sent_DateTime)>
                                        <!--<img src="demo/image1.jpg">-->
                                        <div>
                                            <p>@Html.DisplayFor(modelItem => item.MessageContent)</p>
                                        </div>
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
                <div class="chat-control col-md-12">
                    <input type="text" placeholder="Type a message..." id="textmeesage">
                    <button onclick="onSend()" id="btnSend">Send</button>
                </div>
                    <input type="hidden" value="@ViewBag.Receiver_UserName_onController" id="receiver_UserName_onHtml" />
                    <input type="hidden" value="@ViewBag.Receiver_ID" id="receiver_id_onHtml" />
                </div>
        </div>
    </div>
</body>
</html>
@*@section Chat_info{
        @Html.Action("More Information", "ChatInfo", new { id = @ViewBag.Receiver_ID })
    }*@
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript"> var MyID = '@Session["id"]';</script>
    <script type="text/javascript" src="~/Scripts/ChatBox.js"></script>
}
<script>
    /*************************************/
    /*** when click enter send the message && clear chat box after sending the messege***/
    var input = document.getElementById("textmeesage");
    var send_btn = document.getElementById("btnSend");
    var chatbox = document.getElementById("chat-box-content");

    input.addEventListener("keyup", function (event) {
        event.preventDefault();
        if (event.keyCode === 13) {
            send_btn.click();
            $(input).val("");
        }
    });

    //get the bottom of the chat when send the message
    var chatbox = document.getElementById("chat-box-content");
    chatbox.scrollTop = chatbox.scrollHeight;

</script>

SmartDelivery/Views/NormalCustomer/UpdateProfile.cshtml
@model SmartDelivery.Models.Customer

@{
    ViewBag.Title = "UpdateProfile";
    Layout = "~/Views/Shared/_normalcustomerLayout.cshtml";
}

<h2 class="text-center">Update Profile</h2>

@using (Html.BeginForm("UpdateProfile", "NormalCustomer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-5">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Authorized)
        @Html.HiddenFor(model => model.Active)
        @Html.HiddenFor(model => model.CustomerType)
        @Html.HiddenFor(model => model.ShopName)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="custom-file form-control text-box single-line">

                    <span class="file-name">Selecte Image To Upload  </span>
                    <input class="upload-img" type="file" name="image" id="image" accept="image/*" />
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Update" class="btn" />
            </div>
        </div>
    </div>
}

<a href="@Url.Action("ViewProfile")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>

@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/NormalCustomer/ViewHome.cshtml
@model IEnumerable<SmartDelivery.Models.Offer>

@{
    ViewBag.Title = "My Offers";
    Layout = "~/Views/Shared/_normalcustomerLayout.cshtml";
}

<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>


@*<h2>All Offers</h2>*@

<style>
    /*body {
        background: #f0f0f094;
    }*/

    .price {
        color: #26070778 !important;
        font-size: 15px;
    }
</style>



@foreach (var item in Model)
{
    <div class="col-sm-12 offer-block">

        <div class="col-xs-2 image-section">
            @*@Html.DisplayNameFor(model => model.OfferImages)*@
            <div>
                @foreach (var image in item.OfferImages)
                {
                    var base64 = Convert.ToBase64String(image.Image);
                    var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                    <img src='@imgsrc' style="max-width:150px;max-height:150px" class="img-thumbnail" />
                    break;
                }
            </div>
        </div>

        <div class="col-sm-8 details-section ">
            <div class="col-xs-12 details-header text-center">
                <p class="header-title">
                    @Html.DisplayFor(modelItem => item.OfferDescription)
                </p>
                <span class="price">@Html.DisplayNameFor(model => model.Price)</span>
                <span class="price">@Html.DisplayFor(modelItem => item.Price)</span>
            </div>

            <span>@Html.DisplayNameFor(model => model.Customer.ShopName)</span>
            @Html.DisplayFor(modelItem => item.Customer.ShopName)

            @*<span>@Html.DisplayNameFor(model => model.OfferDescription)</span>
                @Html.DisplayFor(modelItem => item.OfferDescription)*@

            @*@Html.DisplayNameFor(model => model.StartDate)
                @Html.DisplayFor(modelItem => item.StartDate)*@

            @{  string Date = item.EndDate.ToString("dd/MM/yyyy");}
            <span>@Html.DisplayNameFor(model => model.EndDate)</span>
            @Html.DisplayFor(modelItem => Date)


        </div>

        <div class="col-xs-2 order-btn-section">
            @Html.ActionLink("Order", "OrderOffer", new { id = item.ID }, new { @class = "styled_link" })
        </div>

    </div>
                }





@*<script>

        $(".offer-block .image-section img").click(function () {
        console.log("img clicked");
    });
    </script>*@






@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}


@*<!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
        Order
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @using (Ajax.BeginForm("OrderOffer", "NormalCustomer", new { offerID = @offer_Id }, new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "msseageSuccess" }))
                {
                    <div class="modal-body">
                        Enter the quantity you need :
                        <input id="orderQuantity" name="orderQuantity" type="number" min="1" max="100" value="1" />
                    </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <input type="submit" class="btn btn-primary" value="Submit order" />

                                </div>
                }
            </div>
        </div>
    </div>

    <div id="msseageSuccess">

    </div>*@