SmartDelivery/Controllers/SuperVisorController.cs
using SmartDelivery.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SmartDelivery.Controllers
{
    public class SuperVisorController : Controller
    {
        SmartDeliveryEntities db = new SmartDeliveryEntities();

        // GET: SuperVisor
        public ActionResult Index(int? id, int? usertype)
        {
            if (!HomeController.Authenticated && usertype != 2)
            {
                return RedirectToAction("Index", "home");
            }

            if (id != null)
            {
                Employee employee = db.Employees.Find(id);
                Session["userName"] = employee.UserName;
                Session["userType"] = employee.UserType.ToString();
                Session["id"] = id;
                //set cookie to can access from hubs
                Business.SetCookie(id.ToString(), employee.EmployeeType.ToString());
                return View(employee);
            }
            else if (Session["id"] != null)
            {
                int ID = Convert.ToInt32(Session["id"]);
                Employee employee = db.Employees.Find(id);
                return View(employee);
            }


            return RedirectToAction("Index", "home");
        }

        /// <summary>
        /// DeliveryMan Managament //////////////////////////////////////////////////////////////////////
        /// </summary>
        /// 

        [HttpGet]
        public ActionResult ListAllDeliveryMan()
        {
            if (Session["id"] != null)
            {
                //List all employess with usertype "3"
                //without refused with tag "3"
                var deliveryman = db.Employees.Where(s => s.EmployeeType == 3 && s.Authorized != 3 && s.Authorized != -1).ToList();
                return View(deliveryman);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult ListAllRefusedDeliveryMan()
        {
            if (Session["id"] != null)
            {
                //List all employess with usertype "3"
                //refused with tag "3"
                var deliveryman = db.Employees.Where(s => s.EmployeeType == 3 && s.Authorized == 3).ToList();
                return View(deliveryman);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult AddDeliveryMan()
        {
            if (Session["id"] != null)
            {
                //List Of Days 
                ViewBag.HolidayID = new SelectList(db.Days.ToList(), "ID", "DayName");
                //List Of Shifts
                ViewBag.ShiftID = new SelectList(db.Shifts.ToList(), "ID", "StartTime");
                return View();
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult AddDeliveryMan(Employee employee, HttpPostedFileBase image)
        {

            //List Of Days 
            ViewBag.HolidayID = new SelectList(db.Days.ToList(), "ID", "DayName");
            //List Of Shifts
            ViewBag.ShiftID = new SelectList(db.Shifts.ToList(), "ID", "StartTime");

            if (image != null)
            {
                //Save image 
                employee.Photo = new byte[image.ContentLength];
                image.InputStream.Read(employee.Photo, 0, image.ContentLength);

                //check the username of the employee if exits or not 
                Customer checkEmployeeExistInCustomers = new Customer();
                checkEmployeeExistInCustomers = db.Customers.FirstOrDefault(emp => emp.UserName == employee.UserName);

                Employee checkEmployeeExistInEmployees = new Employee();
                checkEmployeeExistInEmployees = db.Employees.FirstOrDefault(emp => emp.UserName == employee.UserName);

                if (checkEmployeeExistInCustomers != null || checkEmployeeExistInEmployees != null)
                {
                    Response.Write("<script>alert('This UserName Is Not Available Type Another One !.');</script>");
                    return View(employee);
                }

                //add employee to database
                Employee myEmployee = new Employee();
                myEmployee.FirstName = employee.FirstName;
                myEmployee.LastName = employee.LastName;
                myEmployee.Email = employee.Email;
                myEmployee.Phone = employee.Phone;
                myEmployee.Address = employee.Address;
                myEmployee.Photo = employee.Photo;
                myEmployee.UserName = employee.UserName;
                myEmployee.PassWord = Encryption.Encrypt(employee.PassWord);
                myEmployee.Salary = employee.Salary;
                myEmployee.Authorized = 2; // => "2" means need to approval
                myEmployee.Active = 0; // means he is Offfline
                myEmployee.EmployeeType = 3; // => "3" the type of the deliveryman
                myEmployee.ShiftID = employee.ShiftID;
                myEmployee.HolidayID = employee.HolidayID;

                db.Employees.Add(myEmployee);
                try
                {
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    Response.Write("<script>alert('invalid Data! Try again.');</script>");
                    return View(employee);

                }

                Response.Write("<script>alert('" + employee.FirstName + " " + employee.LastName + " Added Successfully.');</script>");
                TempData["msg10"] = "<script>alert('" + employee.FirstName + " " + employee.LastName + " Added Successfully.');</script>";


                return RedirectToAction("ListAllDeliveryMan");
            }
            else
            {
                //Check image is submitted or not 
                if (image == null)
                {
                    Response.Write("<script>alert('Select Photo Please.');</script>");
                }

                return View(employee);

            }
        }

        [HttpGet]
        public ActionResult DetailsOfDeliveryMan(int? id)
        {
            if (Session["id"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Employee deliveryMan = db.Employees.FirstOrDefault(D => D.ID == id);

                if (deliveryMan == null)
                {
                    return HttpNotFound();
                }

                return View(deliveryMan);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult UpdateDeliveryMan(int? id)
        {
            if (Session["id"] != null)
            {
                //List Of Days 
                ViewBag.HolidayID = new SelectList(db.Days.ToList(), "ID", "DayName");
                //List Of Shifts
                ViewBag.ShiftID = new SelectList(db.Shifts.ToList(), "ID", "StartTime");


                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Employee deliveryMan = db.Employees.FirstOrDefault(D => D.ID == id);
                if (deliveryMan == null)
                {
                    return HttpNotFound();
                }
                Session["photo"] = deliveryMan.Photo;
                Session["userName"] = deliveryMan.UserName;
                Session["oldPass"] = deliveryMan.PassWord;

                return View(deliveryMan);
            }
            else return RedirectToAction("Index", "home");
        }   

        [HttpPost]
        public ActionResult UpdateDeliveryMan(Employee deliveryMan, HttpPostedFileBase image)
        {
            //List Of Days 
            ViewBag.HolidayID = new SelectList(db.Days.ToList(), "ID", "DayName");
            //List Of Shifts
            ViewBag.ShiftID = new SelectList(db.Shifts.ToList(), "ID", "StartTime");

            if (image != null)
            {
                deliveryMan.Photo = new byte[image.ContentLength];
                image.InputStream.Read(deliveryMan.Photo, 0, image.ContentLength);
            }
            else
            {
                deliveryMan.Photo = (byte[])Session["photo"];
            }

            try
            {

                string oldUserName = Session["userName"].ToString();

                //Check if old username equal to the new or not
                if (deliveryMan.UserName != oldUserName)
                {
                    //check the username of the employee if exits or not 
                    Customer checkEmployeeExistInCustomers = new Customer();
                    checkEmployeeExistInCustomers = db.Customers.FirstOrDefault(emp => emp.UserName == deliveryMan.UserName);

                    Employee checkEmployeeExistInEmployees = new Employee();
                    checkEmployeeExistInEmployees = db.Employees.FirstOrDefault(emp => emp.UserName == deliveryMan.UserName);

                    if (checkEmployeeExistInCustomers != null || checkEmployeeExistInEmployees != null)
                    {
                        Response.Write("<script>alert('This UserName Is Not Available Type Another One !.');</script>");
                        return View(deliveryMan);
                    }
                }
                if (deliveryMan.PassWord != Session["oldPass"].ToString())
                {
                    deliveryMan.PassWord = Encryption.Encrypt(deliveryMan.PassWord);
                }
                db.Entry(deliveryMan).State = EntityState.Modified;
                try
                {
                    db.SaveChanges();
                }

SmartDelivery/Views/SuperVisor/AddDeliveryMan.cshtml
@model SmartDelivery.Models.Employee

@{
    ViewBag.Title = "Add Delivery Man";
    Layout = "~/Views/Shared/_supervisorLayout.cshtml";
}


<h2 class="text-center">Add new delivery man</h2>

@using (Html.BeginForm("AddDeliveryMan", "SuperVisor", FormMethod.Post, new {  enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Authorized)
        @Html.HiddenFor(model => model.Active)
        @Html.HiddenFor(model => model.EmployeeType)
        <div class="col-md-5">

        
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="custom-file form-control text-box single-line">

                    <span class="file-name">Selecte Image To Upload  </span>
                    <input class="upload-img" type="file" name="image" id="image" accept="image/*" />
                </div>
            </div>

        </div>
            </div>
        <div class="col-md-5">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShiftID, "Shift", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ShiftID", null, "-Select Shift-", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ShiftID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HolidayID, "Holiday", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("HolidayID", null, "-Select Holiday-", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.HolidayID, "", new { @class = "text-danger" })
                </div>
            </div>
          
            </div>
        
        </div>
        <div class="form-group">
            <div class=" col-md-12">
                <input type="submit" value="Create" class="btn" />
            </div>
        </div>
}

<a href="@Url.Action("ListAllDeliveryMan")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/SuperVisor/ComplaintToAdmin.cshtml
@model SmartDelivery.Models.Complaint

@{
    ViewBag.Title = "Complaint To Admin";
    Layout = "~/Views/Shared/_supervisorLayout.cshtml";
}

<h2 class="text-center">Send Complaint To Admin</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        @Html.HiddenFor(model => model.DeliveryManID)
        @Html.HiddenFor(model => model.SuperVisorID)

         <div class="form-group text-center">
                 @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                 <div>
                     @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                 </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Send" class="btn" />
            </div>
        </div>
    </div>
}

@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/SuperVisor/ReCreateDeliveryMan.cshtml
@model SmartDelivery.Models.Employee

@{
    ViewBag.Title = "ReCreate DeliveryMan";
    Layout = "~/Views/Shared/_supervisorLayout.cshtml";
}

<h2 class="text-center">Add new delivery man</h2>

@using (Html.BeginForm("ReCreateDeliveryMan", "SuperVisor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Authorized)
        @Html.HiddenFor(model => model.Active)
        @Html.HiddenFor(model => model.EmployeeType)
        <div class="col-md-5">


            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="custom-file form-control text-box single-line">

                        <span class="file-name">Selecte Image To Upload  </span>
                        <input class="upload-img" type="file" name="image" id="image" accept="image/*" />
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" , @type = "password" } })
                    @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShiftID, "Shift", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ShiftID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ShiftID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HolidayID, "Holiday", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("HolidayID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.HolidayID, "", new { @class = "text-danger" })
                </div>
            </div>

        </div>

    </div>
        <div class="form-group">
            <div class=" col-md-12">
                <input type="submit" value="Create" class="btn" />
            </div>
        </div>
}


<p>
    @Html.ActionLink("Back to List", "ListAllRefusedDeliveryMan")
</p>
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/SuperVisor/UpdateDeliveryMan.cshtml
@model SmartDelivery.Models.Employee

@{
    ViewBag.Title = "Update DeliveryMan";
    Layout = "~/Views/Shared/_supervisorLayout.cshtml";
}

<h2 class="text-center">Update DeliveryMan</h2>

@using (Html.BeginForm("UpdateDeliveryMan", "SuperVisor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Authorized)
        @Html.HiddenFor(model => model.Active)
        @Html.HiddenFor(model => model.EmployeeType)


        <div class="col-md-5">
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="custom-file form-control text-box single-line">

                        <span class="file-name">Selecte Image To Upload  </span>
                        <input class="upload-img" type="file" name="image" id="image" accept="image/*" />
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" , @type = "password" } })
                    @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.ShiftID, "ShiftID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ShiftID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ShiftID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HolidayID, "HolidayID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("HolidayID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.HolidayID, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Save" class="btn" />
            </div>
        </div>
    </div>
}

@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}