SmartDelivery/Controllers/AdminController.cs
using SmartDelivery.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SmartDelivery.Controllers
{
    public class AdminController : Controller
    {
        private SmartDeliveryEntities db = new SmartDeliveryEntities();

        public ActionResult getTopRated()
        {
            if (Session["id"] != null)
            {
                var rets = db.Rates.OrderByDescending(r => (r.EmpRate / r.RequestsNumber)).Take(10).ToList();

                if (rets != null)
                {
                    return View(rets);
                }
                else
                {
                    return View();
                }
            }
            else return RedirectToAction("Index", "home");          
        }

      
        // GET: Admin
        public ActionResult Index(int? id , int? usertype)
        {
            if (!HomeController.Authenticated && usertype != 1)
            {
                return RedirectToAction("Index", "home");
            }

            if (id != null)
            {
                Employee employee = db.Employees.Find(id);
                Session["userName"] = employee.UserName;
                Session["userType"] = employee.UserType.ToString();
                Session["id"] = id;
                return View(employee);
            }
            else if (Session["id"] != null)
            {
                int ID = Convert.ToInt32(Session["id"]);
                Employee employee = db.Employees.Find(id);
                return View(employee);
            }


            return RedirectToAction("Index", "home");
        }
        /////////////////// admin profile \\\\\\\\\\\\\\\\\\\\

        [HttpGet]
        public ActionResult ViewProfile()
        {
            if (Session["id"] != null)
            {
                int ID = int.Parse(Session["id"].ToString());

                var admin = db.Employees.FirstOrDefault(n => n.ID == ID);

                if (admin != null)
                {
                    return View(admin);
                }
                else
                {
                    return HttpNotFound();
                }

            }
            else return RedirectToAction("Index", "home");

        }

        [HttpGet]
        public ActionResult UpdateProfile(int? id)
        {
            if (Session["id"] != null)
            {

                int ID = Convert.ToInt32(Session["id"]);

                var admin = db.Employees.FirstOrDefault(s => s.ID == ID);
                if (admin == null)
                {
                    return HttpNotFound();
                }
                Session["photo"] = admin.Photo;
                Session["userName"] = admin.UserName;
                Session["oldPass"] = admin.PassWord;
                return View(admin);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult UpdateProfile(Employee admin, HttpPostedFileBase image)
        {
            if (image != null)
            {
                admin.Photo = new byte[image.ContentLength];
                image.InputStream.Read(admin.Photo, 0, image.ContentLength);
            }
            else
            {
                admin.Photo = (byte[])Session["photo"];
            }

            try
            {

                string oldUserName = Session["userName"].ToString();

                //Check if old username equal to the new or not
                if (admin.UserName != oldUserName)
                {
                    //check the username of the employee if exits or not 
                    Customer checkEmployeeExistInCustomers = new Customer();
                    checkEmployeeExistInCustomers = db.Customers.FirstOrDefault(emp => emp.UserName == admin.UserName);

                    Employee checkEmployeeExistInEmployees = new Employee();
                    checkEmployeeExistInEmployees = db.Employees.FirstOrDefault(emp => emp.UserName == admin.UserName);

                    if (checkEmployeeExistInCustomers != null || checkEmployeeExistInEmployees != null)
                    {
                        Response.Write("<script>alert('This UserName Is Not Available Type Another One !.');</script>");
                        return View(admin);
                    }
                }
                if (admin.PassWord != Session["oldPass"].ToString())
                {
                    admin.PassWord = Encryption.Encrypt(admin.PassWord);
                }

                db.Entry(admin).State = EntityState.Modified;
                db.SaveChanges();
                Response.Write("<script>alert('Customer Updated Successfully .');</script>");

                return RedirectToAction("ViewProfile");
            }
            catch
            {
                return View(admin);
            }
        }
        /////////////////////////////////////
        /// <summary>
        /// Shift Managament //////////////////////////////////////////////////////////////////////
        /// </summary>
        /// 
        public ActionResult ListAllShifts()
        {
            if (Session["id"] != null)
            {
                var shifts = db.Shifts.ToList();
                return View(shifts);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult AddShift()
        {
            if (Session["id"] != null)
            {
                return View();
            }
            else return RedirectToAction("Index", "home");
           
        }

        [HttpPost]
        public ActionResult AddShift(Shift shift)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Shifts.Add(shift);
                    db.SaveChanges();
                    return RedirectToAction("ListAllShifts");
                }

                return View(shift);
            }
            catch
            {
                return View(shift);
            }
        }

        [HttpGet]
        public ActionResult EditShift(int? shiftId)
        {
            if (Session["id"] != null)
            {
                var shift = db.Shifts.Find(shiftId);
                if (shift == null)
                {
                    return HttpNotFound();
                }
                return View(shift);
            }
            else return RedirectToAction("Index", "home");

        }
        [HttpPost]
        public ActionResult EditShift(Shift shift)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(shift).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("ListAllShifts");
                }
                return View(shift);
            }
            catch
            {
                return View(shift);
            }
        }

        [HttpGet]
        public ActionResult DeleteShift(int? shiftId)
        {
            if (Session["id"] != null)
            {
                var shift = db.Shifts.Find(shiftId);
                if (shift == null)
                {
                    return HttpNotFound();
                }
                return View(shift);

            }
            else return RedirectToAction("Index", "home");

        }

        [HttpPost]
        public ActionResult DeleteShift(Shift _shift)
        {
            try
            {
                var myShift = db.Shifts.Find(_shift.ID);
                db.Shifts.Remove(myShift);
                db.SaveChanges();
                return RedirectToAction("ListAllShifts");
               

            }
            catch
            {
                return View(_shift);
            }
        }

        /////////////////////////////////////////////////////////////////////////////////////////
        public ActionResult ListAllCustomers()
        {
            if (Session["id"] != null)
            {
                //List all employess with usertype "2"
                var customers = db.Customers.ToList();
                return View(customers);
            }
            else return RedirectToAction("Index", "home");


        }

        /// <summary>
        /// SuperVisor Managament //////////////////////////////////////////////////////////////////////
        /// </summary>
        /// 

        public ActionResult ListAllSuperVisor()
        {
            if (Session["id"] != null)
            {
                //List all employess with usertype "2"
                var supervisors = db.Employees.Where(s => s.EmployeeType == 2).ToList();
                return View(supervisors);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult AddSuperVisor()
        {
            if (Session["id"] != null)
            {
                //List Of Days 
                ViewBag.HolidayID = new SelectList(db.Days.ToList(), "ID", "DayName");
                //List Of Shifts
                ViewBag.ShiftID = new SelectList(db.Shifts.ToList(), "ID", "StartTime");
                return View();
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult AddSuperVisor(Employee employee, HttpPostedFileBase image)
        {

            //List Of Days 
            ViewBag.HolidayID = new SelectList(db.Days.ToList(), "ID", "DayName");
            //List Of Shifts
            ViewBag.ShiftID = new SelectList(db.Shifts.ToList(), "ID", "StartTime");

            if (image != null)
            {
                //Save image 
                employee.Photo = new byte[image.ContentLength];
                image.InputStream.Read(employee.Photo, 0, image.ContentLength);

SmartDelivery/Views/Admin/AddShift.cshtml
@model SmartDelivery.Models.Shift

@{
    ViewBag.Title = "Add Shift";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2 class="text-center">Add New Shift</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-5">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="StartTime" name="StartTime" type="time" value="" />
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="EndTime" name="EndTime" type="time" value="" />
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Add" class="btn" />
        </div>
    </div>
}

<a href="@Url.Action("ListAllShifts")" class="back">
    <i class="fa fa-arrow-left">Back</i> 
</a>

SmartDelivery/Views/Admin/AddShipmentType.cshtml
@model SmartDelivery.Models.ShipmentType

@{
    ViewBag.Title = "AddShipment Type";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-5">
        <h3 class="text-center">Add shipment type</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerKilo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerKilo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerKilo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn" />
            </div>
        </div>
    </div>
}

<a href="@Url.Action("ListAllShipmentTypes")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>

SmartDelivery/Views/Admin/DetailsOfTheComplaint.cshtml
@model SmartDelivery.Models.Complaint

@{
    ViewBag.Title = "Details Of The Complaint";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2 class="text-center">Details of the complaint</h2>

<div class="center-the-content">
    <hr />

@*Status of DeliveryMan*@
@{
    string status = "";
    if (Model.Employee.Authorized == 1)
    {
        status = "Authorized";
    }
    else if (Model.Employee.Authorized == 0)
    {
        status = "Panned";
    }
}

    <dl class="dl-horizontal">
        
       
            @if (Model.Employee.Photo != null)
            {
                var base64 = Convert.ToBase64String(Model.Employee.Photo);
                var imgsrc = String.Format("data:image/gif;base64,{0}", base64);

                <img src='@imgsrc' style="max-width:200px;max-height:200px" class="img-circle"/>
            }
      
        <dt>
            Complaint Description
        </dt>

        <dd>
            @Html.TextAreaFor(model => model.Description, new { @class = "", @readonly = "readonly" })
        </dd>

        <dt>
            SuperVisor Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee1.FirstName)
            @Html.DisplayFor(model => model.Employee1.LastName)
        </dd>

        <dt>
            SuperVisor UserName
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee1.UserName)
        </dd>

        <dt>
           Delivery Man Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.FirstName)
            @Html.DisplayFor(model => model.Employee.LastName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Employee.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Address)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Employee.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Salary)
        </dd>

        <dt>
            Status
        </dt>

        <dd>
            @status.ToString()
        </dd>

        <dt>
            Holiday
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Day.DayName)
        </dd>

        <dt>
            Shift
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Shift.StartTime)
        </dd>
       

    </dl>
    <p>
        @if (Model.Employee.Authorized == 1)
        {

            using (Html.BeginForm("PanEmployee", "Admin", new { id = Model.Employee.ID, complaintFlag = 1 }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Pan" class="btn-link styled_link" />
            }

        }
        else if (Model.Employee.Authorized == 0)
        {
            using (Html.BeginForm("unPanEmployee", "Admin", new { id = Model.Employee.ID, complaintFlag = 1 }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <input type="submit" value="Authorize" class="btn-link styled_link" />
            }
        }
    </p>
    <a href="@Url.Action("ListAllComplaints")" class="back">
        <i class="fa fa-arrow-left">Back</i>
    </a>
</div>

SmartDelivery/Views/Admin/ListAllCustomers.cshtml
@model IEnumerable<SmartDelivery.Models.Customer>

@{
    ViewBag.Title = "ListAllCustomers";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>List All Customers</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
       
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
       
        
        <td>
            @if (item.Authorized == 1)
            {

                using (Html.BeginForm("PanEmployee", "Admin", new { id = item.ID }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Pan" class="btn-link styled_link done-btn" />
                }

            }
            else
            {
                using (Html.BeginForm("unPanEmployee", "Admin", new { id = item.ID }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Authorize" class="btn-link styled_link done-btn" />
                }
            }
        </td>
    </tr>
}

</table>

SmartDelivery/Views/Admin/ListAllDeliveyMen.cshtml
@model IEnumerable<SmartDelivery.Models.Employee>

@{
    ViewBag.Title = "DeliveyMen";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2 class="text-center">All DeliveyMen</h2>

<table class="table">
    <tr>
        <th>
           Name
        </th>
        <th class="to_be_hidden_firstly">
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th class="to_be_hidden_secondly">
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td class="to_be_hidden_firstly">
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td class="to_be_hidden_secondly">
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>*@
            <td>
                @Html.ActionLink("Details", "DetailsOfDeliveyMen", new { id = item.ID }, new { @class = "styled_link" })

                @if (item.Authorized == 1)
                {

                    using (Html.BeginForm("PanEmployee", "Admin", new { id = item.ID }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Pan" class="btn-link styled_link done-btn" />
                    }

                }
                else if (item.Authorized == 0)
                {
                    using (Html.BeginForm("unPanEmployee", "Admin", new { id = item.ID }, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <input type="submit" value="Authorize" class="btn-link styled_link" />
                    }
                }
            </td>
        </tr>
    }

</table>

SmartDelivery/Views/Admin/ListAllSuperVisor.cshtml
@model IEnumerable<SmartDelivery.Models.Employee>

@{
    ViewBag.Title = "All SuperVisors";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2 class="text-center">All Supervisors</h2>

<p>
    @Html.ActionLink("Add new Supervisor", "AddSuperVisor")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        
        <th class="to_be_hidden_firstly">
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th class="to_be_hidden_secondly">
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Authorized)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            Holiday
        </th>
        <th>
            Shift
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
            @Html.DisplayFor(modelItem => item.LastName)
        </td>

        <td class="to_be_hidden_firstly">
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td class="to_be_hidden_secondly">
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Authorized)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Day.DayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Shift.StartTime)
        </td>*@
        <td> 
            @Html.ActionLink("Details", "DetailsOfSuperVisor", new { id=item.ID }, new { @class = "styled_link" }) 
            @Html.ActionLink("Edit", "UpdateSuperVisor", new { id = item.ID }, new { @class = "styled_link" })
           
            @if (item.Authorized == 1)
            {

                using (Html.BeginForm("PanEmployee", "Admin", new { id = item.ID }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Pan" class="btn-link styled_link done-btn" />
                }

            }
            else
            {
                using (Html.BeginForm("unPanEmployee", "Admin", new { id = item.ID }, FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Authorize" class="btn-link styled_link" />
                }
            }
         </td>
    </tr>
}

</table>

SmartDelivery/Views/Admin/ListAllWaitingDeliveyMenForApproval.cshtml
@model IEnumerable<SmartDelivery.Models.Employee>

@{
    ViewBag.Title = "Waiting DeliveyMen For Approval";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2 class="text-center">Waiting DeliveyMen For Approval</h2>


<table class="table">
    <tr>
        <th>
            Fullname
        </th>
        <th class="to_be_hidden_firstly">
            @Html.DisplayNameFor(model => model.Email)
        </th>
        @*
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
            @Html.DisplayFor(modelItem => item.LastName)
            </td>
        <td class="to_be_hidden_firstly">
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        @*
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>*@
        <td>
            @*@using (Html.BeginForm("AcceptRequest", "Admin", new { id = item.ID }, FormMethod.Post))
            {
            @Html.AntiForgeryToken()
            <input type="submit" value="Accept" class="btn-link styled_link" /> 
            }

            @using (Html.BeginForm("RefuseRequest", "Admin", new { id = item.ID }, FormMethod.Post))
            {
            @Html.AntiForgeryToken()
            <input type="submit" value="Refuse" class="btn-link styled_link" />
            }*@

            @Html.ActionLink("Details", "DetailsOfDeliveyMen", new { id = item.ID }, new { @class = "styled_link" }) 
        </td>
    </tr>
}

</table>

SmartDelivery/Views/Admin/UpdateProfile.cshtml
@model SmartDelivery.Models.Employee

@{
    ViewBag.Title = "UpdateProfile";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2 class="text-center">Update Profile</h2>

@using (Html.BeginForm("UpdateProfile", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-5">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Authorized)
        @Html.HiddenFor(model => model.Active)
      @Html.HiddenFor(model => model.Salary)
        @Html.HiddenFor(model => model.EmployeeType)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="custom-file form-control text-box single-line">

                    <span class="file-name">Selecte Image To Upload  </span>
                    <input class="upload-img" type="file" name="image" id="image" accept="image/*" />
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control" , @type ="password"} })
                @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Update" class="btn" />
            </div>
        </div>
    </div>
}

<a href="@Url.Action("ViewProfile")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>