SmartDelivery/Controllers/ShopController.cs
using SmartDelivery.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SmartDelivery.Controllers
{
    public class ShopController : Controller
    {
        SmartDeliveryEntities db = new SmartDeliveryEntities();

        // GET: Shop
        public ActionResult Index(int? id, int? usertype)
        {
            if (!HomeController.Authenticated && usertype != 5)
            {
                return RedirectToAction("Index", "home");
            }

            if (id != null)
            {
                Customer customer = db.Customers.Find(id);
                Session["userName"] = customer.UserName;
                Session["userType"] = customer.UserType.ToString();
                Session["id"] = id;
                //set cookie to can access from hubs
                Business.SetCookie(id.ToString(), customer.CustomerType.ToString());
                return View(customer);
            }
            else if (Session["id"] != null)
            {
                int ID = Convert.ToInt32(Session["id"]);
                Customer customer = db.Customers.Find(id);
                return View(customer);
            }


            return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult ViewProfile()
        {
            if(Session["id"] != null)
            {
                int shopID = int.Parse(Session["id"].ToString());

                var shop = db.Customers.FirstOrDefault(n => n.ID == shopID);

                if (shop != null)
                {
                    return View(shop);
                }
                else
                {
                    return HttpNotFound();
                }

            }
            else return RedirectToAction("Index", "home");

        }

        [HttpGet]
        public ActionResult UpdateProfile(int? id)
        {
            if (Session["id"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Customer shop = db.Customers.FirstOrDefault(s => s.ID == id);
                if (shop == null)
                {
                    return HttpNotFound();
                }
                Session["photo"] = shop.Photo;
                Session["userName"] = shop.UserName;
                Session["oldPass"] = shop.PassWord;
                return View(shop);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult UpdateProfile(Customer shop, HttpPostedFileBase image)
        {
            if (image != null)
            {
                shop.Photo = new byte[image.ContentLength];
                image.InputStream.Read(shop.Photo, 0, image.ContentLength);
            }
            else
            {
                shop.Photo = (byte[])Session["photo"];
            }

            try
            {

                string oldUserName = Session["userName"].ToString();

                //Check if old username equal to the new or not
                if (shop.UserName != oldUserName)
                {
                    //check the username of the employee if exits or not 
                    Customer checkEmployeeExistInCustomers = new Customer();
                    checkEmployeeExistInCustomers = db.Customers.FirstOrDefault(emp => emp.UserName == shop.UserName);

                    Employee checkEmployeeExistInEmployees = new Employee();
                    checkEmployeeExistInEmployees = db.Employees.FirstOrDefault(emp => emp.UserName == shop.UserName);

                    if (checkEmployeeExistInCustomers != null || checkEmployeeExistInEmployees != null)
                    {
                        Response.Write("<script>alert('This UserName Is Not Available Type Another One !.');</script>");
                        return View(shop);
                    }
                }
                if(shop.PassWord != Session["oldPass"].ToString())
                {
                    shop.PassWord = Encryption.Encrypt(shop.PassWord);
                }

                db.Entry(shop).State = EntityState.Modified;
                db.SaveChanges();
                Response.Write("<script>alert('Customer Updated Successfully .');</script>");

                return RedirectToAction("ViewProfile");
            }
            catch
            {
                return View(shop);
            }
        }

        [HttpGet]
        public ActionResult DeleteAccount(int? id)
        {
            if (Session["id"] != null)
            {
                var shop = db.Customers.Find(id);
                if (shop == null)
                {
                    return HttpNotFound();
                }
                return View(shop);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult DeleteAccount(Customer _shop)
        {
            try
            {
                var shop = db.Customers.Find(_shop.ID);

                if (shop == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    // "0" Means that the shop deleted !
                    shop.Authorized = 0;
                    db.SaveChanges();
                    return RedirectToAction("LogOut", "Home");
                }

            }
            catch
            {
                return View(_shop);
            }
        }


        /// <summary>
        /// Offers Managament //////////////////////////////////////////////////////////////////////
        /// </summary>
        /// 

        public ActionResult ListAllOffers()
        {
            if (Session["id"] != null)
            {
                int shopId = int.Parse(Session["id"].ToString()); //shop Id

                var offers = db.Offers.Where(o => o.ShopID == shopId).ToList();
                return View(offers);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult AddOffer()
        {
            if (Session["id"] != null)
            {
                return View();
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpPost]
        public ActionResult AddOffer(Offer offer , HttpPostedFileBase images)
        {
            try
            {

                    int shopId = int.Parse(Session["id"].ToString()); //shop Id
                int result = DateTime.Compare(offer.StartDate, offer.EndDate);
             
                if (result > 0)
                {
                    Response.Write("<script>alert('Start Date couldnt be later than End date.');</script>");
                    return View(offer);
                }

                if (images != null)
                    {
                           
                            
                                offer.ShopID = shopId;
                                db.Offers.Add(offer);
                                db.SaveChanges();

                                int offerId = offer.ID;  //Offer Id

                                
                                    OfferImage photo = new OfferImage();

                                    photo.Image = new byte[images.ContentLength];
                                    images.InputStream.Read(photo.Image, 0, images.ContentLength);

                                    photo.OfferID = offerId;

                                    db.OfferImages.Add(photo);
                                    db.SaveChanges();
                                    
                                

                                return RedirectToAction("ListAllOffers");
                           }
                    
                    else
                    {
                        //Check image is submitted or not 
                        
                            Response.Write("<script>alert('Select Photo Please.');</script>");
                        
                    }   

                return View(offer);
            }
            catch (Exception ex)
            {
                Response.Write("<script>alert('Exception');</script>");
                Response.Write("<script>alert('"+ex.Message+"');</script>");
               
                return View(offer);
            }
        }

        [HttpGet]
        public ActionResult OfferDetails(int? id)
        {
            if (Session["id"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                Offer offer = db.Offers.FirstOrDefault(o => o.ID == id);

                if (offer == null)
                {
                    return HttpNotFound();
                }

                return View(offer);
            }
            else return RedirectToAction("Index", "home");
        }

        [HttpGet]
        public ActionResult EditOffer(int? id)
        {
            if (Session["id"] != null)
            {
                var offer = db.Offers.Find(id);
                //ده حل لإرور كان مجنني بسبب W3C Specifications
                ViewBag.StartDate = offer.StartDate.ToString("yyyy-MM-ddTHH:mmK");
                ViewBag.EndDate = offer.EndDate.ToString("yyyy-MM-ddTHH:mmK");

                if (offer == null)
                {
                    return HttpNotFound();
                }
                return View(offer);
            }
            else return RedirectToAction("Index", "home");
        }
        [HttpPost]
        public ActionResult EditOffer(Offer offer, HttpPostedFileBase images)
        {
            try
            {

SmartDelivery/Views/Shop/AddOffer.cshtml
@model SmartDelivery.Models.Offer

@{
    ViewBag.Title = "AddOffers";
    Layout = "~/Views/Shared/_shopLayout.cshtml";
}

<h2 class="text-center">Add Offer<span>For One Unit</span></h2>
<style>
    h2{
        position:relative;
    }
    h2>span{
    color: #5B95DE;
    font-size: 15px;
    font-weight: bold;
    bottom: 4px;
    position: absolute;
    margin-left: 5px;
    }
</style>
@using (Html.BeginForm("AddOffer", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-xs-12 add-offer-form">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ShopID)


        <div class="col-md-6 left-part">
            <div class="form-group">
                @Html.LabelFor(model => model.OfferDescription, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.EditorFor(model => model.OfferDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OfferDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { type = "datetime-local", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { type = "datetime-local", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="col-md-6 right-part">
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OfferImages, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    <div class="custom-file form-control text-box single-line">
                        <span class="file-name">Selecte Image</span>
                        <input multiple class="upload-img" type="file" name="images" id="images" accept="image/*" />
                        @* عشان يختار صورة واحدة بس هنرجب مع بعض ناو
                            كنت موديها فين يا لص ^_^ *@
                    </div>
                </div>
            </div>
        </div>


        <div class="add-offer-btn">
            <div class="col-xs-12">
                <input type="submit" value="Add Offer" class="btn" />
            </div>
        </div>
    </div>
}

@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/Shop/CancelRequest.cshtml
@model SmartDelivery.Models.DeliveryRequest

@{
    ViewBag.Title = "CancelRequest";
    Layout = "~/Views/Shared/_shopLayout.cshtml";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script type="text/javascript">

    function initAutocomplete() {

        var geocoder = new google.maps.Geocoder;
       

        var service = new google.maps.DistanceMatrixService();
        var sourceName = '@Model.Source';
        var destinationName = '@Model.Destination';
        var latlngStr1 = sourceName.split(',');
        var latlngStr2 = destinationName.split(',');
        var latlng1 = { lat: parseFloat(latlngStr1[0]), lng: parseFloat(latlngStr1[1]) };
        var latlng2 = { lat: parseFloat(latlngStr2[0]), lng: parseFloat(latlngStr2[1]) };
        
        geocoder.geocode({ 'location': latlng1 }, function (results, status) {
            if (status === 'OK') {
                if (results[0]) {

                    document.getElementById("_from").innerHTML = results[0].formatted_address;

                } else {
                    window.alert('No results found');
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });
        geocoder.geocode({ 'location': latlng2 }, function (results, status) {
            if (status === 'OK') {
                if (results[0]) {

                    document.getElementById("_to").innerHTML = results[0].formatted_address;

                } else {
                    window.alert('No results found');
                }
            } else {
                window.alert('Geocoder failed due to: ' + status);
            }
        });

         
        service.getDistanceMatrix({
            origins: [latlng1],
            destinations: [latlng2],
            travelMode: google.maps.TravelMode.DRIVING,
            unitSystem: google.maps.UnitSystem.METRIC,
            avoidHighways: false,
            avoidTolls: false
        }, function (response, status) {
            if (status == google.maps.DistanceMatrixStatus.OK &&
                            response.rows[0].elements[0].status != "ZERO_RESULTS") {
                var distance = response.rows[0].elements[0].distance.value;
                distance = distance / 1000;

                var duration = response.rows[0].elements[0].duration.value;

                duration = parseFloat(duration / 60).toFixed(2);
                document.getElementById("_calculatedDistance").innerHTML = distance + " km";
                document.getElementById("__deliveryTime").innerHTML = duration + " minutes";

                

            }
        });

        
      


    }//end initAuto


</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARZj829jcIqy8ik7UKOwIT_CynjqIe4e0&libraries=places&callback=initAutocomplete"></script>

<h2 class="text-center">CancelRequest</h2>
<h3 class="text-center">Are you sure you want to Cancel this?</h3>

<div class="center-the-content">
    <hr />
    <dl class="dl-horizontal">
      
        <dt>
            @Html.DisplayNameFor(model => model.ShipmentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShipmentDescription)
        </dd>

        
        <dt>
            @Html.DisplayNameFor(model => model.Source)
        </dt>

        <dd>
            <label id="_from"></label>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            <label id="_to"></label>
        </dd>
        <dt>
            <label>Distance</label>
        </dt>

        <dd>
            <label id="_calculatedDistance"></label>
        </dd>

        <dt>
            <label>Expected Delivery Time</label>
        </dt>

        <dd>
            <label id="__deliveryTime"></label>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancel" class="btn" /> 
        </div>
    }
</div>
<a href="@Url.Action("ListDeliveryRequests")" class="back">
    <i class="fa fa-arrow-left">Back</i>
</a>
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/Shop/DeleteAccount.cshtml
@model SmartDelivery.Models.Customer

@{
    ViewBag.Title = "DeleteAccount";
    Layout = "~/Views/Shared/_shopLayout.cshtml";
}

<h2 class="text-center">DeleteAccount</h2>
<h3 class="text-center">Are you sure you want to delete your Account ?</h3>

<div class="center-the-content">
    <dl class="dl-horizontal">
        <dt>
           Fullname
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShopName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShopName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn" /> 
        </div>
    }
</div>
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/Shop/EditOffer.cshtml
@model SmartDelivery.Models.Offer

@{
    ViewBag.Title = "EditOffer";
    Layout = "~/Views/Shared/_shopLayout.cshtml";
}

<h2 class="text-center">Edit Offer</h2>

@using (Html.BeginForm("EditOffer", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.ShopID)



    <div class="form-horizontal col-xs-12 edit-offer-form">

        <div class="col-md-6 left-part edit-offer-form">
            <div class="form-group">
                @Html.LabelFor(model => model.OfferDescription, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.EditorFor(model => model.OfferDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OfferDescription, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    <input class="form-control text-box single-line" data-val="true" data-val-date="The field StartDate must be a date." data-val-required="The StartDate field is required." id="StartDate" name="StartDate" type="datetime-local" value="@ViewBag.StartDate" />
                    @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    <input class="form-control text-box single-line" data-val="true" data-val-date="The field EndDate must be a date." data-val-required="The EndDate field is required." id="EndDate" name="EndDate" type="datetime-local" value="@ViewBag.EndDate" />
                    @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="col-md-6 right-part">
            <div class="form-group">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OfferImages, htmlAttributes: new { @class = "control-label col-xs-4" })
                <div class="col-xs-8">
                    <div class="custom-file form-control text-box single-line">

                        <span class="file-name">Selecte Image To Upload  </span>
                        <input class="upload-img" type="file" name="images" id="images" accept="image/*" />
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="col-xs-12">
                <input type="submit" value="Update Offer" class="btn edit-offer-btn" /> <br><br />
                <a href="@Url.Action("ListAllOffers")" class="back">
                    <i class="fa fa-arrow-left">Back</i>
                </a>
            </div>
            
        </div>
        
    </div>
    

}



@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/Shop/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_shopLayout.cshtml";
}
@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}

SmartDelivery/Views/Shop/UpdateProfile.cshtml
@model SmartDelivery.Models.Customer

@{
    ViewBag.Title = "UpdateProfile";
    Layout = "~/Views/Shared/_shopLayout.cshtml";
}

<h2 class="text-center">UpdateProfile</h2>

@using (Html.BeginForm("UpdateProfile", "Shop", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Authorized)
        @Html.HiddenFor(model => model.Active)
        @Html.HiddenFor(model => model.CustomerType)
        <div class="col-md-5">
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="custom-file form-control text-box single-line">
                        <span class="file-name">Selecte Image To Upload  </span>
                        <input class="upload-img" type="file" name="image" id="image" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PassWord, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PassWord, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.PassWord, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShopName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShopName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ShopName, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
           
                <div class="col-md-12">
                    <input type="submit" value="Update" class="btn" />
                </div>
            </div>
}

@section scripts {
    <!--will not reffenced as it alreed on layout -->
    <!--<script src="~/Scripts/jquery-3.2.1.min.js"></script> -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript"> var MyType = '@Session["userType"]';</script>
    <script type="text/javascript"> var Myuser_name = '@Session["userName"]';</script>
    <script type="text/javascript" src="~/Scripts/SignalR_AllViews.js"></script>
}